name: Release and Publish Terraform Module

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read version from VERSION file
      id: get_version
      run: echo "::set-output name=version::$(cat VERSION)"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
      continue-on-error: true

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Publish to Terraform Cloud
      env:
        TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
      run: |
        yes "yes" | terraform login
        terraform publish
